export const feedingOptions = {
  infant: {
    "Breast Pump": ["Mechanical Pump", "Electrical Pump"],
    "Breast Feed": ["Direct Feed", "Pumped Feed"],
    Formula: ["Feeding bottle", "Spoon", "Others"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
  toddler: {
    "Breast Pump": ["Mechanical Pump", "Electrical Pump"],
    "Breast Feed": ["Direct Feed", "Pumped Feed"],
    Formula: ["Feeding bottle", "Spoon", "Others"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
  child: {
    "Breast Pump": ["Mechanical Pump", "Electrical Pump"],
    "Breast Feed": ["Direct Feed", "Pumped Feed"],
    Formula: ["Feeding bottle", "Spoon", "Others"],
    "Normal Food": ["Self-fed", "Others-fed"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
  spouse: {
    "Normal Food": ["Self-fed", "Others-fed"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
  friend: {
    "Normal Food": ["Self-fed", "Others-fed"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
  parent: {
    "Normal Food": ["Self-fed", "Others-fed"],
    "Mashed Food": ["Self-fed", "Others-fed"],
    Juice: ["Feeding bottle", "Spoon", "Glass", "Others"],
    Water: ["Feeding bottle", "Spoon", "Glass", "Others"],
  },
};
